apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
spec:
  containers:
  - name: aws-cli
    image: mattelgin/aws-cli:0.0.1
    command: [ "cat" ]
    tty: true
    imagePullPolicy: Always
  serviceAccountName: jenkins